### ISSUE TITLE
question

### ISSUE THREAD

**Issue by surihost** [luxysiv/Cloudflare-Gateway-Package#2]
Is this script faster then the previous one?
what is the actual difference?

**Comment by luxysiv** [comment]
```mode="patch"
cloudflare="run"```
Run with slow speed but script patch list CF
```mode="normal"
cloudflare="run"```
Like `Cloudflare-Gateway-Pihole` repository

**Comment by luxysiv** [comment]
This is only package I was pack script `Cloudflare-Gateway-Pihole`. It works no need install python environment and modules

**Comment by luxysiv** [comment]
No problem if you change `mode="patch"
cloudflare="run"` to `mode="normal"
cloudflare="run"` or vice versa. No need delete CF lists when change mode
