### ISSUE TITLE
how to install on own account

### ISSUE THREAD

**Issue by suricloud** [luxysiv/Cloudflare-Gateway-Package#3]
Hi,

Can you tell how to  install / run gateway package on own github account, without fork from here.

**Comment by luxysiv** [comment]
You can create a new repository, download all assets in this repository and up them to your repository. Add your secret.  Done

**Comment by luxysiv** [comment]
Another way, create a your new repository. Copy link this repository and paste to "Import code" button. Add your secret. Go to setting > action > allow. Run and done

**Comment by suricloud** [comment]
Thanks :)
Can you add also the option for own ddns update with location too,so cloudflare can get the ip and push it to the selected location.

**Comment by luxysiv** [comment]
No, I don't use a router

**Comment by suricloud** [comment]
Ok,no probl.
If you push a update how to update then in my own repository.

**Comment by luxysiv** [comment]
No update, because this package include python and modules needed
