### ISSUE TITLE
Cloudflare Workers to run Github Actions

### ISSUE THREAD

**Issue by suricloud** [luxysiv/Cloudflare-Gateway-Package#4]
Hi,

Will you also update this cloudlare gateway package a with this new update to run github actions with cf workers ?

**Comment by luxysiv** [comment]
Yes I can

**Comment by suricloud** [comment]
Thanks for the update.
I tried with github classic token, but didn''t worked in cf workers.
Can you please explain more in details how to do it?

**Comment by luxysiv** [comment]
![Screenshot_20240531_090017_Edge](https://github.com/luxysiv/Cloudflare-Gateway-Package/assets/46205571/5418678e-3997-4aa4-956a-f2bc6f4f5c19)

**Comment by suricloud** [comment]
I created github token as showed here, creates a cf worker and pasted the code and made the changes as required.
But no succes, i see this error in console;

2worker.js:233 Error: No response!
    at __facade_sw_fetch__ (worker.js:176:15)
    at __facade_invokeChain__ (worker.js:25:12)
    at Object.next (worker.js:22:16)
    at jsonError (worker.js:231:34)
    at __facade_invokeChain__ (worker.js:25:12)
    at Object.next (worker.js:22:16)
    at scheduled (worker.js:213:26)
    at __facade_invokeChain__ (worker.js:25:12)
    at __facade_invoke__ (worker.js:28:12)
    at worker.js:181:43
jsonError @ worker.js:233

**Comment by luxysiv** [comment]
Try all permission and delete all content of old deleloyed on Cloudflare Workers page

**Comment by luxysiv** [comment]
Remember paste you see lastest line if has )} ,delete it

**Comment by suricloud** [comment]
I just pasted this?
Created new cloudflare worker, deleted the existed demo code and then past this with my
github token, github username en repos.

addEventListener('scheduled', event => {
  event.waitUntil(handleScheduledEvent());
});

async function handleScheduledEvent() {
  const GITHUB_TOKEN = 'YOUR_GITHUB_TOKEN_HERE';
  try {
    const dispatchResponse = await fetch('https://api.github.com/repos/YOUR_USER_NAME/YOUR_REPO_NAME/actions/workflows/main.yml/dispatches', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${GITHUB_TOKEN}`,
        'Content-Type': 'application/json',
        'User-Agent': 'Mozilla/5.0',
      },
      body: JSON.stringify({
        ref: 'main'
      }),
    });

    if (!dispatchResponse.ok) throw new Error('Failed to dispatch workflow');
  } catch (error) {
    console.error('Error handling scheduled event:', error);
  }
}

**Comment by luxysiv** [comment]
Change your toke, your account and repository name. Example :
`https://api.github.com/repos/luxysiv/Cloudflare-Gateway-Pihole/actions/workflows/main.yml/dispatches`

**Comment by suricloud** [comment]
![Screenshot 2024-06-01 074207](https://github.com/luxysiv/Cloudflare-Gateway-Package/assets/43868361/826d4df6-1ae1-47ce-b274-89b983aeb0b1)

**Comment by suricloud** [comment]
> Change your toke, your account and repository name. Example : `https://api.github.com/repos/luxysiv/Cloudflare-Gateway-Pihole/actions/workflows/main.yml/dispatches`

I have done, still getting same errors in console?

**Comment by luxysiv** [comment]
Try, I was test. It's work

**Comment by luxysiv** [comment]
> I created github token as showed here, creates a cf worker and pasted the code and made the changes as required. But no succes, i see this error in console;
> 
> 2worker.js:233 Error: No response! at **facade_sw_fetch** (worker.js:176:15) at **facade_invokeChain** (worker.js:25:12) at Object.next (worker.js:22:16) at jsonError (worker.js:231:34) at **facade_invokeChain** (worker.js:25:12) at Object.next (worker.js:22:16) at scheduled (worker.js:213:26) at **facade_invokeChain** (worker.js:25:12) at **facade_invoke** (worker.js:28:12) at worker.js:181:43 jsonError @ worker.js:233

Don't care About log error 
![Screenshot_20240601_180037_Edge](https://github.com/luxysiv/Cloudflare-Gateway-Package/assets/46205571/f318cf8f-7920-4818-a241-d393f1154b31)
![Screenshot_20240601_180125_Edge](https://github.com/luxysiv/Cloudflare-Gateway-Package/assets/46205571/8320cc5a-bc7f-4aba-90cd-dacee5212677)
![Screenshot_20240601_180145_Edge](https://github.com/luxysiv/Cloudflare-Gateway-Package/assets/46205571/5a4da7ed-fe2b-44f2-a287-e7f6e2aa9131)

**Comment by suricloud** [comment]
can you sent the full screenshot of cf workers you added? mine seems to be different and my errors are different en in red color.
Something is not good my side.Want to know where and what to correct.

**Comment by luxysiv** [comment]
> can you sent the full screenshot of cf workers you added? mine seems to be different and my errors are different en in red color. Something is not good my side.Want to know where and what to correct.

The same, see my console log. Don't worry about it.Code is ok

**Comment by suricloud** [comment]
should cron trigger to be set to 1 minute?
This will update then update github and filters evry minute?

**Comment by luxysiv** [comment]
1 day, Github Action limited

**Comment by suricloud** [comment]
ok,thanks.
Will see how this work out :)

**Comment by luxysiv** [comment]
![Screenshot_20240604_082947_Edge](https://github.com/luxysiv/Cloudflare-Gateway-Package/assets/46205571/2ba221b0-dced-4770-94b6-9186b73ef44e)
It's easy to configure.

**Comment by suricloud** [comment]
ok :)

**Comment by luxysiv** [comment]
Code now won’t fail if Cloudflare’s server is normal
